name: EditSigns
main: tld.sima.editsigns.Main
version: 0.1
api-version: 1.13
author: Simon A
description: A plugin that allows users to edit already placed signs

permissions:
  editsign:
    description: Allows user to see edit signs
    permission: es.use
    permission-message: You don't have the es.use permission.
  